### ISSUE TITLE
Erro 500

### ISSUE THREAD

**Issue by ViniciusHass** [Treinamento-Stefa-IA-DevOps/treinamento-dia-04-08-Lukeover#1]
https://github.com/Treinamento-Stefa-IA-DevOps/treinamento-dia-04-08-Lukeover/blob/cdaa49b6e738c37e6c73eaf275bcb18d62b973a0/tarefa/codigo/main.py#L16

Boa Tarde @Lukeover  ** Lukas Barbosa de Oliveira**,

Seu codigo quebrou na linha acima.

**Comment by Lukeover** [comment]
Boa tarde @ViniciusHass correção enviada junto com a alteração da mensagem para o usuário.
